cmake_minimum_required(VERSION 3.15...3.26)
project(${SKBUILD_PROJECT_NAME} LANGUAGES CXX)
message(STATUS "Building ${SKBUILD_PROJECT_NAME}")
set(PYBIND11_FINDPYTHON ON)
find_package(pybind11 CONFIG REQUIRED)
add_subdirectory(lib)
pybind11_add_module(_mercury MODULE "src/mercury/binding.cpp" "src/mercury/axial.cpp" "src/mercury/formula1.cpp" "src/mercury/formulav.cpp" "src/mercury/formulaxy.cpp" "src/mercury/lrm.cpp" "src/mercury/rec.cpp")
target_include_directories(_mercury PRIVATE include)
target_link_libraries(_mercury PRIVATE Mercury)
install(TARGETS _mercury DESTINATION ${SKBUILD_PROJECT_NAME})